languageCode = "en"
defaultContentLanguage = "en"
title = "IT Forge"
baseurl = "https://www.itforge.nl/"
theme = "nix"
#disableKinds = ["page", "section", "taxonomy", "taxonomyTerm"]

[Author]
    name = "Leander Janssen"
    bio = "Freelance Cloud/DevOps Solutions Engineer"

[params]
    Name = "Leander Janssen"
    HeaderUsername = "leander"
    HeaderHostname = "itforge.nl"
    About = """
    Hi, I'm a Freelance Cloud/DevOps Solutions Engineer.
    I provide consultancy, support and design services for cloud, container and linux environments.
    As a certified and accredited trainer for Docker, Kubernetes and Hashicorp I can also deliver 
    various trainings and workshops in the container technology space.
    """
    ProfilePicture  = "https://www.itforge.nl/images/portrait.jpg"
    GithubID = "leanderjanssen/"
    LinkedInID = "leanderjanssen/"
    Email = "info@itforge.nl"
