languageCode = "en"
defaultContentLanguage = "en"
title = "IT Forge"
baseurl = "https://www.itforge.nl/"
theme = "nix"
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm"]

[Author]
    name = "Leander Janssen"
    bio = "Freelance Cloud/DevOps Solutions Engineer"

[params]
    Name = "Leander Janssen"
    HeaderUsername = "leander"
    HeaderHostname = "itforge.nl"
    About = "Freelance Cloud/DevOps Solutions Engineer"
    ProfilePicture  = "https://s.gravatar.com/avatar/3e89f9dd7e69fa1ae3a82abc712c8d88?s=80"
    GithubID = "https://github.com/leanderjanssen/"
    LinkedInID = "https://www.linkedin.com/in/leanderjanssen/"
    Email = "mailto:info@itforge.nl"
