languageCode = "en"
defaultContentLanguage = "en"
title = "IT Forge"
baseurl = "https://www.itforge.nl/"
theme = "nix"
#disableKinds = ["page", "section", "taxonomy", "taxonomyTerm"]

[Author]
    name = "IT Forge"
    bio = "Native Clou and DevOps Solutions Engineers"

[params]
    Name = "Leander Janssen"
    HeaderUsername = "leander"
    HeaderHostname = "itforge.nl"
    About = """
    We provide consultancy, support and design services in the following areas: 

    - Cloud (Azure, AWS, Google)
    - Linux (Red Hat, Ubuntu, Debian)
    - Container solutions (Docker, Kubernetes)
    - Automation (Terraform, Ansible, Puppet, Bash, Python)
    - CI/CD (Github Actions, Gitlab CI, Jenkins)
    - Virtualization (KVM, VMWare)

    We also employ certified and accredited trainers for Docker, Hashicorp and Kubernetes.
    We can also deliver various trainings and workshops in the container technology space.
    """
    ProfilePicture  = "https://www.itforge.nl/images/itforge.png"
    GithubID = "leanderjanssen/"
    LinkedInID = "leanderjanssen/"
    Email = "info@itforge.nl"
