languageCode = "en"
defaultContentLanguage = "en"
title = "IT Forge"
baseurl = "https://www.itforge.nl/"
theme = "nix"
#disableKinds = ["page", "section", "taxonomy", "taxonomyTerm"]

[Author]
    name = "Leander Janssen"
    bio = "Freelance Cloud/DevOps Solutions Engineer"

[params]
    Name = "Leander Janssen"
    HeaderUsername = "leander"
    HeaderHostname = "itforge.nl"
    About = """
    Freelance Cloud/DevOps Solutions Engineer<br>
    I provide consultancy, support and design services in the following areas:<br>
    """
    ProfilePicture  = "https://www.itforge.nl/images/portrait.jpg"
    GithubID = "leanderjanssen/"
    LinkedInID = "leanderjanssen/"
    Email = "info@itforge.nl"
